

- name: instalando pacotes pardoes para debian
  package:
   name:
    - htop
    - vim
    - sysstat
    - cowsay
  when: ansible_os_family == "Debian"

- name: instalando pacotes para centos
  package:
   name:
    - epel-release
    - vim
    - sysstat
  when: ansible_os_family == "RedHat"
