---
# tasks file for confbase

- name: playbook de criacao de usuario
  include: user.yaml

- name: playbook de instalacao de pacotes
  include: install.yaml

- name: playbook de arquivos padroes
  include: files.yaml

