
- name: criando os usuarios padroes para todas as maquinas
  user:
   name: "{{item.nome}}"
   password: "{{item.senha}}"
   state: "{{item.estado}}"
   home: "{{item.casa}}"
  with_items:
    - { nome: cicero, senha: '$1$lFW5vz9g$oOA4zOSsHeOuNYQrEa.BA1', estado: present, casa: /srv/cicero }
    - { nome: developer, senha: '$1$lFW5vz9g$oOA4zOSsHeOuNYQrEa.BA1', estado: present, casa: /srv/developer }
    - { nome: devops, senha: '$1$lFW5vz9g$oOA4zOSsHeOuNYQrEa.BA1', estado: present, casa: /srv/devops }


