---
# tasks file for web
- name: Web  para debian
  package:
   name: apache2
  when: ansible_os_family == "Debian"

- name: Web para redhat
  package:
   name: httpd
  when: ansible_os_family == "RedHat"

- name: start httpd
  service:
   name: httpd
   state: started
  when: ansible_os_family == "RedHat"

- name: enviando um arquivo template
  template:
   src: templates/index.html
   dest: /var/www/html/index.html


